baseURL = 'https://github.com/setup-windows-debloat/setup-windows-debloat.github.io/'
languageCode = 'pt-br'
title = 'Windows Debloat!'
theme = [] # Mantemos vazio para usar o layout customizado abaixo
